#!/usr/bin/env bash

# a Bash script that displays listening ports:
# That only shows listening sockets
# That shows the PID and name of the program to which each socket belongs

sudo ss -tulp | grep 'LISTEN' | awk '{print "PID: " $7, "Program: " $9}'
