#!/usr/bin/env bash
#checks whether it has received an argument on the command line; if it hasn't, it displays a usage message, otherwise it pings the IP address passed as an argument 5 times

if [ $# -ne 1 ]
then #"then" marque le début du bloc d'instructions conditionnelles
	echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
else
	ping -c 5 "$1"
fi #mot-clé standard pour marquer la fin d'une structure conditionnelle "if"
